---
  - name: Disable Root SSH login
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "^PermitRootLogin"
      line: "PermitRootLogin no"
      validate: 'sshd -t -f %s'
    notify: restart ssh
