---
- name: Check if Helm binary exists.
  stat:
    path: "{{ helm_bin_path }}"
  register: helm_check

- name: Check Latest Helm release version (requires login to gh cli).
  #shell: gh api repos/helm/helm/releases -q '.[0].name'
  shell: curl  "https://api.github.com/repos/helm/helm/tags" | jq -r '.[0].name'
  failed_when: false
  changed_when: false
  register: helm_latest_version

- name: Check for new stable version
  debug:
    msg: > 
      - "A newer version of helm exists!""
      - "Current target version is {{ helm_version }}.""
      - "Latest stable version is {{ helm_latest_version.stdout }}."
  when: >
    not helm_check.stat.exists
    or helm_version not in helm_latest_version.stdout
- name: Check Helm version.
  command: "{{ helm_bin_path }} version"
  failed_when: false
  changed_when: false
  register: helm_existing_version

- name: Download helm.
  unarchive:
    src: "{{ helm_repo_path }}/helm-{{ helm_version }}-{{ helm_platform }}-{{ helm_arch }}.tar.gz"
    dest: /tmp
    remote_src: true
    mode: 0755
  register: helm_download
  when: >
    not helm_check.stat.exists
    or helm_version not in helm_existing_version.stdout
- name: Copy helm binary into place.
  copy:
    src: "/tmp/{{ helm_platform }}-{{ helm_arch }}/helm"
    dest: "{{ helm_bin_path }}"
    mode: 0755
    remote_src: true
  become: true
  when: helm_download is changed

- name: Install Helm Diff Plugin
  kubernetes.core.helm_plugin:
    plugin_path: https://github.com/databus23/helm-diff
    state: present