---
  - name: Add Crossplane repository
    kubernetes.core.helm_repository:
      name: crossplane-stable
      repo_url: https://charts.crossplane.io/stable

  - name: Helm Repo Update
    command: helm repo update
    changed_when: false

  - name: Create Crossplane namespace
    kubernetes.core.k8s:
      name: crossplane-system
      api_version: v1
      kind: Namespace
      state: present

  - name: Install Crossplane chart
    kubernetes.core.helm:
        name: crossplane
        namespace: crossplane-system
        chart_ref: crossplane-stable/crossplane
        values_files: 
          - local-ansible/helm/crossplane/values.yaml

  - name: Fetch Crossplane cli
    ansible.builtin.uri:
      url: https://raw.githubusercontent.com/crossplane/crossplane/master/install.sh
      return_content: yes
    register: crossplane_cli_installer

  - name: Run Crossplane cli installer
    ansible.builtin.shell:
      cmd: sh
      stdin: "{{ crossplane_cli_installer.content }}"