---
  - name: Add Argo repository
    kubernetes.core.helm_repository:
      name: argo
      repo_url: https://argoproj.github.io/argo-helm

  - name: Helm Repo Update
    command: helm repo update
    changed_when: false

  - name: Create Argo namespace
    kubernetes.core.k8s:
      name: argocd
      api_version: v1
      kind: Namespace
      state: present

  - name: Deploy Argo chart
    kubernetes.core.helm:
        name: argocd-server
        namespace: argocd
        chart_ref: argo/argo-cd
        values_files: 
          - include/helm/argocd/values.yaml

  - name: Apply Yaml for ArgoCD
    kubernetes.core.k8s:
      definition: "{{ lookup('template', '{{ item }}') | from_yaml }}"
    with_fileglob:
      - "k8s/argocd/*.yaml"