---
  - name: Add Jetstack repository
    kubernetes.core.helm_repository:
      repo_name: jetstack
      repo_url: https://charts.jetstack.io
      repo_state: present

  - name: Helm Repo Update
    command: helm repo update
    changed_when: false