---
- name: Install zsh
  package:
    name: zsh
    state: latest
  become: true

- name: Install oh my zsh
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    depth: 1

- name: Copy zshrc
  copy:
    src: files/zshrc
    dest: ~/.zshrc
    mode: 0644

- name: Install zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: ~/.oh-my-zsh//custom/plugins/zsh-autosuggestions
    depth: 1

- name: Install zsh-syntaxhighlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.oh-my-zsh//custom/plugins/zsh-syntax-highlighting
    depth: 1

- name: Change Default Shell
  shell: chsh -s $(which zsh)
  become: true