---
- hosts: localhost
  gather_facts: true

  tasks:
    - name: Get nodes
      command: kubectl get nodes
      register: current_nodes
      changed_when: false

    - name: Print nodes
      debug:
        msg: "{{ current_nodes.stdout }}"

    - name: include cert-manager
      import_tasks: local-ansible/jetstack-helm.yml

    - name: include traefik
      import_tasks: local-ansible/traefik-helm.yml

    - name: include Longhorn
      import_tasks: local-ansible/longhorn-helm.yml

    - name: include Argo CD
      import_tasks: local-ansible/argocd-helm.yml

#    - name: include Crossplane
#      import_tasks: local-ansible/crossplane-helm.yml

    - name: include Airflow
      import_tasks: local-ansible/airflow-helm.yml

#    - name: include Loki
#      import_tasks: local-ansible/loki-helm.yml

#    - name: include Bitnami
#      import_tasks: local-ansible/bitnami-helm.yml
